# Generated by Django 2.2 on 2021-01-03 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addition_type', models.CharField(max_length=128, unique=True, verbose_name='附加收费')),
            ],
            options={
                'verbose_name': '附加费用类型',
                'verbose_name_plural': '附加费用类型',
            },
        ),
        migrations.CreateModel(
            name='CostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costtype', models.CharField(max_length=64, unique=True, verbose_name='收费类型')),
            ],
            options={
                'verbose_name': '收费类型表',
                'verbose_name_plural': '收费类型表',
            },
        ),
        migrations.CreateModel(
            name='ExperimentList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_num', models.CharField(max_length=64, unique=True, verbose_name='项目编号')),
                ('sample_num', models.PositiveSmallIntegerField(verbose_name='样本数量')),
                ('name_terminal', models.CharField(blank=True, max_length=128, null=True, verbose_name='送样终端')),
                ('name', models.CharField(max_length=32, verbose_name='送样人')),
                ('date_preperation', models.CharField(blank=True, max_length=32, null=True, verbose_name='制备完成')),
                ('date_test', models.CharField(blank=True, max_length=64, null=True, verbose_name='上机日期')),
                ('date_searchlib', models.CharField(blank=True, max_length=64, null=True, verbose_name='搜库日期')),
                ('date_senddata', models.CharField(blank=True, max_length=64, null=True, verbose_name='数据发送')),
                ('pro_cost', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='项目金额')),
                ('deadline_pro', models.CharField(blank=True, max_length=64, null=True, verbose_name='项目截止日期')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='数据库文件')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('addition_cost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.AdditionalCost', verbose_name='附加收费')),
                ('cost_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.CostType', verbose_name='收费等级')),
            ],
            options={
                'verbose_name': '项目列表',
                'verbose_name_plural': '项目列表',
                'ordering': ['experiment_num'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=64, unique=True, verbose_name='上机仪器')),
            ],
            options={
                'verbose_name': '仪器类型',
                'verbose_name_plural': '仪器类型',
            },
        ),
        migrations.CreateModel(
            name='PayType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='结算方式')),
            ],
            options={
                'verbose_name': '结算方式',
                'verbose_name_plural': '结算方式',
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projecttype', models.CharField(max_length=64, unique=True, verbose_name='项目类型')),
                ('pro_period', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='项目周期')),
            ],
            options={
                'verbose_name': '项目类型表',
                'verbose_name_plural': '项目类型表',
            },
        ),
        migrations.CreateModel(
            name='ProManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_manager', models.CharField(max_length=128, unique=True, verbose_name='项目经理')),
            ],
            options={
                'verbose_name': '项目经理列表',
                'verbose_name_plural': '项目经理列表',
            },
        ),
        migrations.CreateModel(
            name='ReimburseMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(max_length=128, verbose_name='报账材料')),
            ],
            options={
                'verbose_name': '报账材料类型',
                'verbose_name_plural': '报账材料类型',
            },
        ),
        migrations.CreateModel(
            name='RequireInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_content', models.CharField(max_length=128, verbose_name='开票要求')),
            ],
            options={
                'verbose_name': '开票要求类型',
                'verbose_name_plural': '开票要求类型',
            },
        ),
        migrations.CreateModel(
            name='ResPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '实验负责人',
                'verbose_name_plural': '实验负责人',
            },
        ),
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampletype', models.CharField(max_length=64, unique=True, verbose_name='样本类型')),
            ],
            options={
                'verbose_name': '样本类型表',
                'verbose_name_plural': '样本类型表',
            },
        ),
        migrations.CreateModel(
            name='SupinformationExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_info', models.CharField(max_length=128, unique=True, verbose_name='实验偏差')),
            ],
            options={
                'verbose_name': '实验偏差类型',
                'verbose_name_plural': '实验偏差类型',
            },
        ),
        migrations.CreateModel(
            name='TypeApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_type', models.CharField(max_length=128, verbose_name='开票类型')),
            ],
            options={
                'verbose_name': '开票类型表',
                'verbose_name_plural': '开票类型表',
            },
        ),
        migrations.CreateModel(
            name='UnitInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=128, unique=True, verbose_name='开票单位')),
            ],
            options={
                'verbose_name': '开票单位',
                'verbose_name_plural': '开票单位',
                'ordering': ['unit_name'],
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_num', models.CharField(max_length=128, verbose_name='合同编号')),
                ('num_invoice', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='发票号')),
                ('unit_invoice', models.CharField(blank=True, max_length=128, null=True, verbose_name='开票单位')),
                ('date_invoice', models.CharField(blank=True, max_length=64, null=True, verbose_name='申请开票日期')),
                ('cost_invoice', models.PositiveIntegerField(blank=True, null=True, verbose_name='发票金额')),
                ('date_post', models.CharField(blank=True, max_length=64, null=True, verbose_name='发票寄送日期')),
                ('num_express', models.CharField(blank=True, max_length=64, null=True, verbose_name='发票快递单号')),
                ('date_callback', models.CharField(blank=True, max_length=64, null=True, verbose_name='合同回收日期')),
                ('void_red', models.NullBooleanField(verbose_name='作废或冲红')),
                ('date_payment', models.CharField(blank=True, max_length=64, null=True, verbose_name='回款日期')),
                ('pay_check', models.NullBooleanField(verbose_name='是否结清')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pro_num', models.ManyToManyField(to='projects.ExperimentList', verbose_name='项目编号')),
            ],
            options={
                'verbose_name': '开票回款表',
                'verbose_name_plural': '开票回款表',
                'ordering': ['c_time'],
            },
        ),
        migrations.AddField(
            model_name='experimentlist',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Machine', verbose_name='上机仪器'),
        ),
        migrations.AddField(
            model_name='experimentlist',
            name='pay_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.PayType', verbose_name='结算方式'),
        ),
        migrations.AddField(
            model_name='experimentlist',
            name='pro_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ProManager', verbose_name='项目经理'),
        ),
        migrations.AddField(
            model_name='experimentlist',
            name='pro_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectType', verbose_name='项目类型'),
        ),
        migrations.AddField(
            model_name='experimentlist',
            name='res_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ResPerson', verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='experimentlist',
            name='sam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.SampleType', verbose_name='样本类型'),
        ),
        migrations.AddField(
            model_name='experimentlist',
            name='supply_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.SupinformationExp', verbose_name='实验偏差'),
        ),
        migrations.AddField(
            model_name='experimentlist',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.UnitInvoice', verbose_name='送样单位'),
        ),
        migrations.CreateModel(
            name='ApplyInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_num', models.CharField(max_length=128, verbose_name='合同编号')),
                ('new_unit', models.CharField(blank=True, max_length=128, null=True, verbose_name='新单位名称')),
                ('duty_paragraph', models.CharField(blank=True, max_length=256, null=True, verbose_name='税号')),
                ('bank', models.CharField(blank=True, max_length=128, null=True, verbose_name='开户行')),
                ('account', models.CharField(blank=True, max_length=128, null=True, verbose_name='银行账号')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='单位地址')),
                ('phone', models.CharField(blank=True, max_length=128, null=True, verbose_name='联系电话')),
                ('cost_invoice', models.PositiveIntegerField(verbose_name='发票金额')),
                ('sheet_num', models.PositiveSmallIntegerField(verbose_name='开票张数')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='合同文件')),
                ('list_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='项目清单')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='检测报告')),
                ('address_linkman', models.CharField(blank=True, max_length=256, null=True, verbose_name='收件人信息')),
                ('red_invoice', models.PositiveIntegerField(blank=True, null=True, verbose_name='冲红发票号')),
                ('note', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('person_apply', models.CharField(blank=True, max_length=32, null=True, verbose_name='申请人')),
                ('status', models.CharField(choices=[('applying', '申请中'), ('finish', '已完成'), ('refuse', '已拒绝')], default='申请中', max_length=32, verbose_name='状态')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('pro_num', models.ManyToManyField(to='projects.ExperimentList', verbose_name='项目编号')),
                ('require_invoice', models.ManyToManyField(blank=True, to='projects.RequireInvoice', verbose_name='开票要求')),
                ('type_apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.TypeApply', verbose_name='开票类型')),
                ('unit_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.UnitInvoice', verbose_name='开票单位')),
            ],
            options={
                'verbose_name': '开票申请总表',
                'verbose_name_plural': '开票申请总表',
                'ordering': ['-c_time'],
            },
        ),
    ]
