# Generated by Django 2.2 on 2021-01-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210105_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepayment',
            name='person_apply',
            field=models.CharField(default=1, max_length=32, verbose_name='申请人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoicepayment',
            name='date_invoice',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='开票日期'),
        ),
    ]
