# Generated by Django 2.2 on 2021-01-09 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210106_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyinvoice',
            name='red_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.InvoicePayment', verbose_name='原发票号'),
        ),
    ]
