# Generated by Django 2.2 on 2021-01-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210109_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyinvoice',
            name='person_apply',
            field=models.CharField(default=1, max_length=32, verbose_name='申请人'),
            preserve_default=False,
        ),
    ]
