# Generated by Django 2.2 on 2021-01-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210109_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyinvoice',
            name='red_invoice',
        ),
        migrations.AddField(
            model_name='applyinvoice',
            name='red_invoice',
            field=models.ManyToManyField(blank=True, to='projects.InvoicePayment', verbose_name='原发票号'),
        ),
    ]
