# Generated by Django 2.2 on 2021-01-11 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210111_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyinvoice',
            name='red_invoice',
        ),
        migrations.AddField(
            model_name='applyinvoice',
            name='red_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.InvoicePayment', verbose_name='原发票号'),
        ),
    ]
