# Generated by Django 2.2 on 2021-01-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20210111_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyinvoice',
            name='red_invoice',
        ),
        migrations.AddField(
            model_name='applyinvoice',
            name='red_invoice',
            field=models.ManyToManyField(blank=True, to='projects.InvoicePayment', verbose_name='原发票号'),
        ),
    ]
