# Generated by Django 2.2 on 2021-01-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20210111_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyinvoice',
            name='status',
            field=models.CharField(choices=[('applying', '申请中'), ('passed', '已通过'), ('refused', '已拒绝')], default='applying', max_length=32, verbose_name='状态'),
        ),
    ]
