# Generated by Django 2.2 on 2021-01-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20210111_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentlist',
            name='addition_cost',
        ),
        migrations.AddField(
            model_name='experimentlist',
            name='addition_cost',
            field=models.ManyToManyField(blank=True, to='projects.AdditionalCost', verbose_name='附加收费'),
        ),
    ]
