# Generated by Django 2.2 on 2021-01-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_invoicepayment_void_red'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyinvoice',
            name='status',
            field=models.CharField(choices=[('AI', '申请中'), ('PD', '已通过'), ('RD', '已拒绝')], default='AI', max_length=32, verbose_name='状态'),
        ),
    ]
